ci: accept build scan ToS via argument

diff --git a/.github/workflows/pr_tests.yml b/.github/workflows/pr_tests.yml
--- a/.github/workflows/pr_tests.yml
+++ b/.github/workflows/pr_tests.yml
@@ -9,29 +9,33 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
-      - uses: actions/checkout@v4
-      - uses: gradle/actions/wrapper-validation@v4.2.2
-      - name: Validate charset
-        run: |
-          set -x
-          git config core.quotepath off
-          for file in $(git ls-files | grep -v '\.jpg$'); do
-            encoding=$(file -b --mime-encoding "$file")
-            if [ "$encoding" != "utf-8" ] && [ "$encoding" != "us-ascii" ] && [ "$encoding" != "binary" ]; then
-              echo "$file has invalid encoding: $encoding"
-              exit 1
-            fi
-          done
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: '21'
-          distribution: 'temurin'
-          server-id: github
-          settings-path: ${{ github.workspace }}
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@7ba6b1c82014ba7e124420b8688ca6a4ddb25b7b
-      - name: Build and test with Gradle
-        run: ./gradlew clean build test --scan
+    - uses: actions/checkout@v4
+    - name: Validate charset
+      run: |
+        set -x
+        git config core.quotepath off
+        for file in $(git ls-files | grep -v '\.jpg$'); do
+          encoding=$(file -b --mime-encoding "$file")
+          if [ "$encoding" != "utf-8" ] && [ "$encoding" != "us-ascii" ] && [ "$encoding" != "binary" ]; then
+            echo "$file has invalid encoding: $encoding"
+            exit 1
+          fi
+        done
+    - name: Set up JDK 21
+      uses: actions/setup-java@v4
+      with:
+        java-version: '21'
+        distribution: 'temurin'
+        server-id: github
+        settings-path: ${{ github.workspace }}
+    - name: Setup Gradle
+      uses: gradle/actions/setup-gradle@v4
+      with:
+        build-scan-publish: true
+        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
+        build-scan-terms-of-use-agree: "yes"
+        validate-wrappers: true
+        add-job-summary-as-pr-comment: on-failure
+    - name: Build and test with Gradle
+      run: ./gradlew clean build test
