ci: check the coverage on PRs and output it for each commit

diff --git a/.github/workflows/pr_tests.yml b/.github/workflows/pr_tests.yml
--- a/.github/workflows/pr_tests.yml
+++ b/.github/workflows/pr_tests.yml
@@ -38,4 +38,25 @@ jobs:
         validate-wrappers: true
         add-job-summary-as-pr-comment: on-failure
     - name: Build and test with Gradle
-      run: ./gradlew clean build test
+      run: ./gradlew clean build test jacocoTestReport
+
+    - name: Parse coverage percentage
+      id: coverage
+      run: |
+        COVERAGE=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" build/reports/jacoco/test/jacocoTestReport.xml)
+        MISSED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" build/reports/jacoco/test/jacocoTestReport.xml)
+        TOTAL=$((COVERAGE + MISSED))
+        PERCENTAGE=$(awk "BEGIN {printf \"%.2f\", ($COVERAGE / $TOTAL) * 100}")
+        if [$COVERAGE * 100 < $]
+        echo "coverage=50" >> $GITHUB_ENV
+        echo "coverage=50" >> $GITHUB_OUTPUT
+
+    - name: Check coverage threshold
+      run: |
+        THRESHOLD=70.0 # Set your desired minimum coverage percentage
+        if (( $(echo "$PERCENTAGE < $THRESHOLD" | bc -l) )); then
+          echo "Test coverage ($COVERAGE%) is below the threshold ($THRESHOLD%). Failing the workflow."
+          exit 1
+        fi
+      env:
+        COVERAGE: ${{ env.coverage }}
